title: Slime Physics Simulation
description: WebSim project exported to GitHub Pages
show_downloads: false
google_analytics:
theme: minima

plugins:
  - jekyll-feed
  - jekyll-sitemap

# Disable Jekyll processing for certain directories
exclude:
  - node_modules/
  - .github/
  - README.md
  - LICENSE

# Include all files (don't ignore dotfiles by default)
include:
  - .htaccess

# Markdown settings
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge
